import { Property } from "@/components/PropertyCard";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Luxury 4 Bedroom Detached Duplex",
    price: "₦87,000,000",
    location: "Lekki Phase 1, Lagos",
    sqft: "3500 sqft",
    beds: 4,
    baths: 5,
    tag: "For Sale",
    agentName: "Chioma Okeke",
    agentInitials: "CO",
  },
  {
    id: "2",
    title: "Modern 3 Bedroom Apartment",
    price: "₦120,000,000",
    location: "Ikoyi, Lagos",
    sqft: "2800 sqft",
    beds: 3,
    baths: 4,
    tag: "For Sale",
    agentName: "Emeka Nwosu",
    agentInitials: "EN",
  },
  {
    id: "3",
    title: "Elegant 5 Bedroom Mansion",
    price: "₦250,000,000",
    location: "Maitama, Abuja",
    sqft: "5200 sqft",
    beds: 5,
    baths: 6,
    tag: "For Sale",
    agentName: "Amaka Obi",
    agentInitials: "AO",
  },
  {
    id: "4",
    title: "Furnished 2 Bedroom Flat",
    price: "₦800,000/yr",
    location: "Wuse 2, Abuja",
    sqft: "1200 sqft",
    beds: 2,
    baths: 2,
    tag: "For Rent",
    agentName: "Tunde Bello",
    agentInitials: "TB",
  },
  {
    id: "5",
    title: "Executive 3 Bedroom Terrace",
    price: "₦1,200,000/yr",
    location: "Ikeja GRA, Lagos",
    sqft: "1800 sqft",
    beds: 3,
    baths: 3,
    tag: "For Rent",
    agentName: "Ngozi Eze",
    agentInitials: "NE",
  },
  {
    id: "6",
    title: "Luxury Studio Apartment",
    price: "₦150,000/night",
    location: "Victoria Island, Lagos",
    sqft: "650 sqft",
    beds: 1,
    baths: 1,
    tag: "Shortlet",
    agentName: "Kola Adeyemi",
    agentInitials: "KA",
  },
  {
    id: "7",
    title: "Spacious 4 Bedroom Bungalow",
    price: "₦55,000,000",
    location: "Trans Amadi, Port Harcourt",
    sqft: "2600 sqft",
    beds: 4,
    baths: 3,
    tag: "For Sale",
    agentName: "Sade Okonkwo",
    agentInitials: "SO",
  },
  {
    id: "8",
    title: "Brand New 2 Bedroom Flat",
    price: "₦600,000/yr",
    location: "Surulere, Lagos",
    sqft: "900 sqft",
    beds: 2,
    baths: 2,
    tag: "For Rent",
    agentName: "Ibrahim Musa",
    agentInitials: "IM",
  },
];

export const forSaleProperties = mockProperties.filter((p) => p.tag === "For Sale");
export const forRentProperties = mockProperties.filter((p) => p.tag === "For Rent");
export const shortletProperties = mockProperties.filter((p) => p.tag === "Shortlet");
